version: "3"
services:
  mongo:
    container_name: mongodb
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  server:
    container_name: nest
    image: node:18
    working_dir: /usr/src/back-end-nest-js
    restart: always
    command: bash -c "npm install -g @nestjs/cli && npm install --only=prod && npm run start"
    environment:
      - MONGO_URL=mongodb://mongo:27017/nest
    volumes:
      - .:/usr/src/back-end-nest-js
      - ./package.json:/usr/src/back-end-nest-js/package.json
    ports:
      - "3000:3000" # server
      - "9222:9222" # debug
    links:
      - mongo
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000" # acesso padrão do minio
      - "9001:9001" # interface web para o console web do minio => http://localhost:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio:/data
      - ./minio/config:/root/.minio
    command: server --console-address :9001 /data
    restart: always